name: Playwright

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/config.json'
      - 'bin/**'
      - '.gitignore'
      - 'docs/**'
  schedule:
    - cron: '30 08 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      reporter:
        required: false
        description: 'Select a reporter'
        type: choice
        options:
          - allure-playwright
          - html
          - blob
          - list
        default: allure-playwright
      path-to-results:
        required: false
        description: 'Provide path to reporter files'
        default: allure-results
        type: choice
        options:
          - test-results/
          - tests/playwright/blob-report
          - allure-results
      fail_fast:
        type: boolean
        required: true
        description: 'Cancel tests when one of them fails'
        default: false

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Playwright:
    name: Playwright test - ${{ matrix.shardIndex }} on PHP 8.0
    runs-on: ubuntu-latest
    needs: [build-plugin]
    if: ${{ github.event.pull_request.title == null || needs.build-plugin.outputs.changelog_diff }}
    strategy:
      fail-fast: ${{ inputs.fail_fast || false }}
      matrix:
        shardIndex: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "elements-regression", "known-issues" ]
        shardTotal: [ 10 ]
    outputs:
      known_issues_failed: ${{ steps.set_known_issues_failure.outputs.known_issues_failed }}
    steps:
      # ... (other steps)

      - name: Set known issues failure output
        if: ${{ failure() && matrix.shardIndex == 'known-issues' }}
        id: set_known_issues_failure
        run: echo "known_issues_failed=true"
        env:
          known_issues_failed: "true"
        shell: bash

      - name: Export known issues output
        if: ${{ failure() && matrix.shardIndex == 'known-issues' }}
        run: echo "::set-output name=known_issues_failed::true"

  test-result:
    needs: Playwright
    if: ${{ always() }} # Will run even if 'Playwright' matrix is skipped
    runs-on: ubuntu-22.04
    name: Playwright - Test Results
    steps:
      - name: Debug known_issues_failed variable
        run: echo "known_issues_failed is ${{ needs.Playwright.outputs.known_issues_failed }}"

      - name: Test status
        run: echo "Test status is - ${{ needs.Playwright.result }}"

      - name: Send Slack message for known issues
        if: ${{ needs.Playwright.outputs.known_issues_failed == 'true' }}
        uses: ./.github/workflows/post-to-slack
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_TAG_CHANNELS: ${{ secrets.TEST_AUTOMATION_RESULTS }}
          PAYLOAD: |
            {
              "text": "Elementor Core: Playwright with WordPress nightly has known issues: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Elementor Core: Playwright with WordPress nightly has known issues: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }

      - name: Check Playwright matrix status
        if: ${{ needs.Playwright.result != 'success' && needs.Playwright.result != 'skipped' }}
        run: exit 1



