name: Playwright

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/config.json'
      - 'bin/**'
      - '.gitignore'
      - 'docs/**'
  schedule:
    - cron: '30 08 * * 0,1,2,3,4,5'
  workflow_dispatch:
    inputs:
      reporter:
        required: false
        description: 'Select a reporter'
        type: choice
        options:
          - allure-playwright
          - html
          - blob
          - list
        default: allure-playwright
      path-to-results:
        required: false
        description: 'Provide path to reporter files'
        default: allure-results
        type: choice
        options:
          - test-results/
          - tests/playwright/blob-report
          - allure-results
      fail_fast:
        type: boolean
        required: true
        description: 'Cancel tests when one of them fails'
        default: false

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-plugin:
    name: Build plugin
    uses: ./.github/workflows/build.yml

  Playwright:
    name: Playwright test - ${{ matrix.shardIndex }} on PHP 8.0
    runs-on: ubuntu-latest
    needs: [build-plugin]
    if: ${{ github.event.pull_request.title == null || needs.build-plugin.outputs.changelog_diff }}
    strategy:
      fail-fast: ${{ inputs.fail_fast || false }}
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "elements-regression", "known-issues"]
        shardTotal: [10]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          sed -i -e "s/image: 'mariadb:lts'/image: 'mariadb:11.2.4-jammy'/g" node_modules/@wordpress/env/lib/build-docker-compose-config.js
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-plugin.outputs.artifact_name }}
          path: ./build
      - name: Update wp-env.json file
        env:
          PHP_VERSION: '8.0'
          WP_CORE_VERSION: 'latest'
        run: node ./.github/scripts/build-wp-env.js
      - name: Install WordPress environment
        run: |
          npm run start-local-server
      - name: Update WordPress to nightly build
        run: npx wp-env run cli wp core update https://wordpress.org/nightly-builds/wordpress-latest.zip
      - name: Setup test data
        run: npm run test:setup:playwright
      - name: Install playwright/test
        run: |
          npx playwright install chromium
      - name: Run Playwright tests
        if: ${{ matrix.shardIndex != 'elements-regression' && matrix.shardIndex != 'known-issues' }}
        run: npm run test:playwright -- --grep-invert="@known-issue" --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=${{ inputs.reporter || 'list,github' }}
      - name: Run element regression tests
        if: ${{ matrix.shardIndex == 'elements-regression' }}
        run: npm run test:playwright:elements-regression -- --reporter=${{ inputs.reporter || 'list,github' }}
      - name: Run tests with known issues
        if: ${{ matrix.shardIndex == 'known-issues' }}
        run: |
          set -e
          echo "Running known issues tests..."
          npm run test:playwright -- --grep="@known-issue" --reporter=${{ inputs.reporter || 'list,github' }}
          if [ $? -ne 0 ]; then
            echo "I am well known" > known-issues-status.txt
          else
            echo "No known issue failures" > known-issues-status.txt
          fi
      - name: Debug known issues status file
        if: ${{ matrix.shardIndex == 'known-issues' }}
        run: |
          echo "Checking known issues file..."
          ls -la
          cat known-issues-status.txt
      - name: Upload known issues status
        if: ${{ matrix.shardIndex == 'known-issues' }}
        uses: actions/upload-artifact@v4
        with:
          name: known-issues
          path: known-issues-status.txt

  test-result:
    needs: Playwright
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    name: Playwright - Test Results
    steps:
      - name: Test status
        run: echo "Test status is - ${{ needs.Playwright.result }}"
      - name: Download known issues status
        if: ${{ needs.Playwright.result == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: known-issues
          path: known-issues-status.txt
      - name: Debug known issues artifact
        if: ${{ needs.Playwright.result == 'failure' }}
        run: |
          echo "Checking downloaded artifact..."
          ls -la
          cat known-issues-status.txt
      - name: Send Slack message for known issues
        if: ${{ needs.Playwright.result == 'failure' && github.event_name == 'schedule' }}
        uses: ./.github/workflows/post-to-slack
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_TAG_CHANNELS: ${{ secrets.TEST_AUTOMATION_RESULTS }}
          PAYLOAD: |
            {
              "text": "Elementor Core: Playwright known issues test has failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Known Issues Playwright Test has failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
